name: Crystal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Crystal
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            crystal \
            libssl-dev \
            libreadline-dev \
            libz-dev \
            libyaml-dev \
            libffi-dev
          
      - name: Install shards
        run: |
          curl -sSL https://github.com/crystal-lang/shards/releases/download/0.10.1/shards-0.10.1-linux-x86_64.tar.gz | tar xz -C /usr/local/bin

      - name: Install dependencies
        run: shards install
