name: Crystal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Crystal
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            crystal \
            libssl-dev \
            libreadline-dev \
            libz-dev \
            libyaml-dev \
            libffi-dev

      - name: Install dependencies
        run: shards install