name: Crystal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # Job for Ubuntu
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Crystal and dependencies on Ubuntu
      - name: Install Crystal
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            crystal \
            libssl-dev \
            libreadline-dev \
            libz-dev \
            libyaml-dev \
            libffi-dev

      # Install shards (Crystal's dependency manager)
      - name: Install shards
        run: |
          sudo apt-get install -y shards

      # Install dependencies using shards
      - name: Install dependencies
        run: shards install

  # Job for macOS latest (macOS 12 or higher)
  macos-latest:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      # Install Crystal and dependencies on macOS
      - name: Install Crystal
        run: |
          brew install crystal

      # Install dependencies using shards
      - name: Install dependencies
        run: shards install
