name: Crystal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Install Crystal and dependencies
      - name: Install Crystal
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            crystal \
            libssl-dev \
            libreadline-dev \
            libz-dev \
            libyaml-dev \
            libffi-dev

      # Install shards (Crystal's dependency manager)
      - name: Install shards
        run: |
          sudo apt-get install -y shards

      # Install dependencies using shards
      - name: Install dependencies
        run: shards install
